name: CI
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    env:
      DOCKER_IMAGE: ghcr.io/kamatera/cloudcli-server-kubernetes:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -LsSf https://astral.sh/uv/0.6.14/install.sh | sh &&\
          uv sync &&\
          uv run pytest &&\
          docker build -t ${DOCKER_IMAGE} --build-arg VERSION=${{ github.sha }} . &&\
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin &&\
          docker push ${DOCKER_IMAGE}
